Models/DataBaseSetting.cs
namespace JournalVersion.Models
{
    public class DataBaseSetting
    {
        public int ID { get; set; }
        public int SolutionID { get; set; }
        public string DatabaseName { get; set; }
        public string DatabaseServer { get; set; }
        public string DataBaseSGBD { get; set; }
        public string DatabaseHost { get; set; }
        public string DatabasePWD { get; set; }
        public string DatabaseComment { get; set; }

        public Solution Solution { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace JournalVersion.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/IISSetting.cs
namespace JournalVersion.Models
{
    public class IISSetting
    {
        public int ID { get; set; }
        public int SolutionID { get; set; }
        public string IISHostName { get; set; }
        public string Port { get; set; }
        public string IISComment { get; set; }

        public Solution Solution { get; set; }
    }
}

Models/Solution.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JournalVersion.Models
{
    public class Solution
    {
        public int ID { get; set; }
        public string SolutionName { get; set; }

        // Quel framework est utilisé
        public string SolutionType { get; set; }
        public string SolutionComment { get; set; }

        // Quels manips ont été faites dessus
        public string SolutionNote { get; set; }
        public DateTime SolutionDateStart { get; set; }
        public DateTime SolutionDateEnd { get; set; }

        public virtual ICollection<IISSetting> IISSettings { get; set; }
        public virtual ICollection<DataBaseSetting> DataBaseSettings { get; set; }
        public virtual ICollection<UserApplicationTest> UserApplicationTests { get; set; }
    }
}

Models/UserApplicationTest.cs
namespace JournalVersion.Models
{
    public class UserApplicationTest
    {
        public int ID { get; set; }
        public int SolutionID { get; set; }
        public string UserTestLogin { get; set; }
        public string UserTestEmail { get; set; }
        public string UserTestPWD { get; set; }
        public string UserTestComment { get; set; }

        public Solution Solution { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using JournalVersion.Models;

namespace JournalVersion.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SolutionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JournalVersion.Data;
using JournalVersion.Models;

namespace JournalVersion.Controllers
{
    public class SolutionsController : Controller
    {
        private readonly JournalContext _context;

        public SolutionsController(JournalContext context)
        {
            _context = context;
        }

        // GET: Solutions
        public async Task<IActionResult> Index()
        {
            return View(await _context.Solutions.ToListAsync());
        }

        // GET: Solutions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var solution = await _context.Solutions
                .SingleOrDefaultAsync(m => m.ID == id);
            if (solution == null)
            {
                return NotFound();
            }

            return View(solution);
        }

        // GET: Solutions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Solutions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,SolutionName,SolutionType,SolutionComment,SolutionNote,SolutionDateStart,SolutionDateEnd")] Solution solution)
        {
            if (ModelState.IsValid)
            {
                _context.Add(solution);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(solution);
        }

        // GET: Solutions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var solution = await _context.Solutions.SingleOrDefaultAsync(m => m.ID == id);
            if (solution == null)
            {
                return NotFound();
            }
            return View(solution);
        }

        // POST: Solutions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,SolutionName,SolutionType,SolutionComment,SolutionNote,SolutionDateStart,SolutionDateEnd")] Solution solution)
        {
            if (id != solution.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(solution);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SolutionExists(solution.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(solution);
        }

        // GET: Solutions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var solution = await _context.Solutions
                .SingleOrDefaultAsync(m => m.ID == id);
            if (solution == null)
            {
                return NotFound();
            }

            return View(solution);
        }

        // POST: Solutions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var solution = await _context.Solutions.SingleOrDefaultAsync(m => m.ID == id);
            _context.Solutions.Remove(solution);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SolutionExists(int id)
        {
            return _context.Solutions.Any(e => e.ID == id);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JournalVersion</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">JournalVersion</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Solutions" asp-action="Index">Solutions</a>
                    </li>
                    <!--
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">Courses</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Instructors" asp-action="Index">Instructors</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Departments" asp-action="Index">Departments</a>
                    </li>
                    -->
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - JournalVersion</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Solutions/Create.cshtml
@model JournalVersion.Models.Solution

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>Solution</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SolutionName" class="control-label"></label>
                <input asp-for="SolutionName" class="form-control" />
                <span asp-validation-for="SolutionName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SolutionType" class="control-label"></label>
                <input asp-for="SolutionType" class="form-control" />
                <span asp-validation-for="SolutionType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SolutionComment" class="control-label"></label>
                <input asp-for="SolutionComment" class="form-control" />
                <span asp-validation-for="SolutionComment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SolutionNote" class="control-label"></label>
                <input asp-for="SolutionNote" class="form-control" />
                <span asp-validation-for="SolutionNote" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SolutionDateStart" class="control-label"></label>
                <input asp-for="SolutionDateStart" class="form-control" />
                <span asp-validation-for="SolutionDateStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SolutionDateEnd" class="control-label"></label>
                <input asp-for="SolutionDateEnd" class="form-control" />
                <span asp-validation-for="SolutionDateEnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Solutions/Delete.cshtml
@model JournalVersion.Models.Solution

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Solution</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SolutionName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SolutionName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SolutionType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SolutionType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SolutionComment)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SolutionComment)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SolutionNote)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SolutionNote)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SolutionDateStart)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SolutionDateStart)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SolutionDateEnd)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SolutionDateEnd)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Solutions/Details.cshtml
@model JournalVersion.Models.Solution

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Solution</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SolutionName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SolutionName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SolutionType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SolutionType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SolutionComment)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SolutionComment)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SolutionNote)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SolutionNote)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SolutionDateStart)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SolutionDateStart)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SolutionDateEnd)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SolutionDateEnd)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Solutions/Edit.cshtml
@model JournalVersion.Models.Solution

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>Solution</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="SolutionName" class="control-label"></label>
                <input asp-for="SolutionName" class="form-control" />
                <span asp-validation-for="SolutionName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SolutionType" class="control-label"></label>
                <input asp-for="SolutionType" class="form-control" />
                <span asp-validation-for="SolutionType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SolutionComment" class="control-label"></label>
                <input asp-for="SolutionComment" class="form-control" />
                <span asp-validation-for="SolutionComment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SolutionNote" class="control-label"></label>
                <input asp-for="SolutionNote" class="form-control" />
                <span asp-validation-for="SolutionNote" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SolutionDateStart" class="control-label"></label>
                <input asp-for="SolutionDateStart" class="form-control" />
                <span asp-validation-for="SolutionDateStart" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SolutionDateEnd" class="control-label"></label>
                <input asp-for="SolutionDateEnd" class="form-control" />
                <span asp-validation-for="SolutionDateEnd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Solutions/Index.cshtml
@model IEnumerable<JournalVersion.Models.Solution>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.SolutionName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SolutionType)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SolutionComment)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SolutionNote)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SolutionDateStart)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SolutionDateEnd)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SolutionName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SolutionType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SolutionComment)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SolutionNote)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SolutionDateStart)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SolutionDateEnd)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>